CREATE TABLE `daplink_log` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`dt` DATETIME NULL DEFAULT NULL,
	`request` TEXT NULL,
	`response` TEXT NULL,
	`entityid` INT(19) NULL DEFAULT NULL,
	`daplinkid` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
